# Generated by Django 3.2.10 on 2022-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
