# Generated by Django 3.2.10 on 2022-10-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0003_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review_text', models.TextField(default='')),
                ('Review_username', models.CharField(max_length=50)),
            ],
        ),
    ]
