# Generated by Django 3.2.10 on 2022-11-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0005_auto_20221115_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='RequestStatus',
            field=models.IntegerField(default=1),
        ),
    ]
