# Generated by Django 3.2.10 on 2022-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0007_alter_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery_image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
