# Generated by Django 3.2.10 on 2022-11-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0009_auto_20221125_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
