# Generated by Django 3.2.10 on 2022-12-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0012_remove_review_wholeno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='half',
        ),
    ]
