# Generated by Django 3.2.10 on 2022-12-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0014_alter_feedback_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[('5', '5'), ('4.5', '4.5'), ('4', '4'), ('3.5', '3.5'), ('3', '3'), ('2.5', '2.5')], default=5),
        ),
    ]
