# Generated by Django 3.2.10 on 2022-12-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VR_Chest_App', '0015_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(choices=[(5, '5'), (4.5, '4.5'), (4, '4'), (3.5, '3.5'), (3, '3'), (2.5, '2.5')], default=5),
        ),
    ]
